/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unum_ukv_DataBase */

#ifndef _Included_com_unum_ukv_DataBase
#define _Included_com_unum_ukv_DataBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unum_ukv_DataBase
 * Method:    transaction
 * Signature: ()Lcom/unum/ukv/Transaction;
 */
JNIEXPORT jobject JNICALL Java_com_unum_ukv_DataBase_transaction
  (JNIEnv *, jobject);

/*
 * Class:     com_unum_ukv_DataBase
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unum_ukv_DataBase_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_unum_ukv_DataBase
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_unum_ukv_DataBase_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_unum_ukv_DataBase
 * Method:    close_
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unum_ukv_DataBase_close_1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
